services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: queue
      POSTGRES_PASSWORD: queue
      POSTGRES_DB: queue_db
    ports:
      - "5432:5432"
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U queue -d jobs"]
      interval: 2s
      timeout: 3s
      retries: 15

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy